### ISSUE TITLE
Search commands returning errors

### ISSUE THREAD

**Issue by minervamaga** [moiph/ub3r-b0t#18]
I have hunted quite a bit trying to solve this and can't find an answer.  My server has repeatedly been getting the following error message when trying to use .b, .g, or .img.

> No results found. [ Shared search limit reached for the day.  Provide your own API key in the admin panel to maintain limits for your own server]

Nothing I can find in the documentation explains how to fix this and I'm not very familiar with the code side of the bots to hunt it down myself.  

Love the bot and utilize it everywhere, thank you in advance!
(Ps: A Møøse once bit my sister)

**Comment by moiph** [comment]
These types of questions should come to the support server, https://ub3r-b0t.com/join
But since you used the magic phrase from reading the docs, it warmed my heart and I updated the FAQ to help. https://ub3r-b0t.com/docs/articles/faq.html#im-getting-an-error-about-shared-search-limits
If there is still uncertainty please stop by the server.

**Comment by minervamaga** [comment]
Thank you so much.  I try to avoid support servers like the plague XD The FAQ update was more than enough to point me in the right direction!
